import React, { useEffect, useState } from "react";
import api from "../../Config/Axios";
import jsPDF from "jspdf";
import {
  FaCheckCircle,
  FaTimesCircle,
  FaClock,
  FaDownload,
  FaFileMedicalAlt,
} from "react-icons/fa";

function PatientReports() {


  const [reports, setReports] = useState([]);
  const [activeTab, setActiveTab] = useState("all");
  const [showReport, setShowReport] = useState({});
  const [selectedReport, setSelectedReport] = useState(null);
  const [stats, setStats] = useState({
    total: 0,
    accepted: 0,
    rejected: 0,
    pending: 0,
  });

  useEffect(() => {
    fetchReports();
    fetchStats();
  }, []);














  
  const fetchReports = async () => {
    try {
      const res = await api.get("/api/appointmentPatient/getAllAppointment");
      setReports(res.data);
    } catch (err) {
      console.log(err);
    }
  };

  const fetchStats = async () => {
    try {
      const response = await api.get("/api/doctorAppointment/AppointmentStats");
      setStats(response.data);
    } catch (error) {
      console.log(error);
    }
  };




const handleDownload = (report) => {
  const doc = new jsPDF();

 
  doc.setFontSize(18);
  doc.setTextColor(0, 48, 78);
  doc.text("MediCore Hospital", 20, 20);

  doc.setFontSize(14);
  doc.text("Medical Report", 20, 28);

 
  doc.setDrawColor(200);
  doc.line(20, 32, 190, 32);

  
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  doc.text(`Patient Name: ${report.firstName}`, 20, 45);
  doc.text(`Department: ${report.department || "General"}`, 20, 52);
  doc.text(`Date: ${new Date(report.appDate).toLocaleDateString()}`, 20, 59);
  doc.text(`Contact: ${report.mobNumber}`, 20, 66);
  doc.text(`Room No: ${report.roomNum || "-"}`, 20, 73);

 
  doc.setFontSize(12);
  doc.setTextColor(150, 0, 0);
  doc.text("Health Issue:", 20, 85);

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(report.healthIssue || "No issue", 20, 92);

 
  doc.setFontSize(12);
  doc.setTextColor(0, 100, 0);
  doc.text("Doctor Note:", 20, 105);

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(report.doctorNote || "No note", 20, 112);


  doc.setFontSize(12);
  doc.setTextColor(0, 0, 150);
  doc.text("Medicines:", 20, 125);

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  if (report.medicines?.length) {
    let y = 132;
    report.medicines.forEach((med, index) => {
      doc.text(
        `${index + 1}. ${med.name} - ${med.dosage}`,
        20,
        y
      );
      y += 7;
    });
  } else {
    doc.text("No medicines prescribed", 20, 132);
  }

  
  doc.setFontSize(12);
  doc.setTextColor(180, 120, 0);
  doc.text("Follow-up:", 20, 150);

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(report.followUp || "No follow-up", 20, 157);

 
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text("Generated by MediCore Hospital System", 20, 180);

 
  doc.save(`${report.firstName}_Medical_Report.pdf`);
};




  const filteredReports =
    activeTab === "all"
      ? reports
      : reports.filter((r) => r.bookingStatus === activeTab);

  return (
    <div className="min-h-screen ">
      <div className="max-w-[1200px] mx-auto">

        {/* HEADER */}
        <div className="mb-8 flex items-center gap-3">
          <div className="p-3 bg-gradient-to-r from-[#00304e] to-[#005f73] rounded-xl shadow-lg">
            <FaFileMedicalAlt className="text-white text-2xl" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-[#00304e]">
              My Medical Reports
            </h1>
            <p className="text-gray-500 text-sm">
              Access your medical records
            </p>
          </div>
        </div>

        {/* FILTER */}
        <div className="flex gap-3 mb-6 flex-wrap">
          {["all", "accepted", "rejected", "pending"].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 rounded-full text-sm capitalize ${
                activeTab === tab
                  ? "bg-[#00304e] text-white"
                  : "bg-white  text-gray-600"
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* CARDS */}




        {filteredReports.length === 0 ? (
  <div className="flex flex-col items-center justify-center py-16 text-center w-full col-span-full">
    
    {/* ICON */}
    <div className="w-16 h-16 flex items-center justify-center rounded-full bg-gray-100 mb-4">
      <FaFileMedicalAlt className="text-gray-400 text-2xl" />
    </div>

    {/* MESSAGE */}
    <h2 className="text-lg font-semibold text-gray-600">
      {activeTab === "pending" && "No pending appointments"}
      {activeTab === "accepted" && "No confirmed appointments"}
      {activeTab === "rejected" && "No rejected appointments"}
      {activeTab === "all" && "No reports available"}
    </h2>

    {/* SUBTEXT */}
    <p className="text-sm text-gray-400 mt-1">
      {activeTab === "pending" && "Your new bookings will appear here"}
      {activeTab === "accepted" && "Approved appointments will be shown here"}
      {activeTab === "rejected" && "Declined appointments will be listed here"}
      {activeTab === "all" && "Start by booking an appointment"}
    </p>
  </div>
) : (
  
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            
          {filteredReports.map((item) => {
            const isAccepted = item.bookingStatus === "accepted";
            const isReady = isAccepted && item.reportSent;

            // UX MESSAGE
            let message = "";
            let bannerStyle = "";

            if (item.bookingStatus === "pending") {
              message = "Your appointment is awaiting confirmation from the doctor";
              bannerStyle = "bg-amber-50 text-amber-700";
            } else if (item.bookingStatus === "rejected") {
              message = "Your appointment was not approved. Please rebook.";
              bannerStyle = "bg-red-50 text-red-600";
            } else if (isAccepted && !item.reportSent) {
              message = "Your report is being prepared";
              bannerStyle = "bg-green-50 text-green-600";
            } else if (isReady) {
              message = "Your report is ready";
              bannerStyle = "bg-blue-50 text-blue-600";
            }

            return (
              <div
                key={item._id}
                className="bg-white rounded-2xl shadow-sm hover:shadow-xl transition p-5 "
              >
                {/* STATUS BANNER */}
                <div className={`text-xs px-3 py-2 rounded-lg mb-3 ${bannerStyle}`}>
                  {message}
                </div>

                {/* TOP */}
                <div className="flex justify-between mb-3">
                  <div>
                    <h2 className="font-semibold text-[#00304e]">
                      {item.firstName}
                    </h2>
                    <p className="text-xs text-gray-400">
                      {item.department || "General"}
                    </p>
                  </div>

                  <span
                    className={`text-xs px-3 py-1 rounded-full flex items-center gap-1 ${
                      item.bookingStatus === "accepted"
                        ? "bg-emerald-50 text-emerald-600"
                        : item.bookingStatus === "rejected"
                        ? "bg-red-50 text-red-500"
                        : "bg-amber-50 text-amber-600"
                    }`}
                  >
                    {item.bookingStatus === "accepted" && <FaCheckCircle />}
                    {item.bookingStatus === "rejected" && <FaTimesCircle />}
                    {item.bookingStatus === "pending" && <FaClock />}
                    {item.bookingStatus}
                  </span>
                </div>

              
                <div className="text-sm text-gray-600 space-y-1 mb-3">
                  <p>📅 {new Date(item.appDate).toLocaleDateString()}</p>
                  <p>📞 {item.mobNumber}</p>
                  <p>🏥 Room {item.roomNum || "—"}</p>
                </div>

               
                <div className="mb-3">
                  <p className="text-xs text-gray-400">Health Issue</p>
                  <p className="text-sm">{item.healthIssue || "No issue"}</p>
                </div>

              
              {isAccepted && (
 <button
  onClick={() => setSelectedReport(item)}
  className="flex items-center gap-2 text-sm bg-gradient-to-r from-[#00304e] to-[#005f73] text-white px-4 py-2 rounded-lg shadow hover:scale-105 transition"
>
  <FaFileMedicalAlt /> View Report
</button>
)}
          

                {/* FULL REPORT ONLY WHEN READY */}
                {isReady && showReport[item._id] && (
                  <div className="bg-gray-50 p-3 rounded-lg text-sm space-y-2">

                    <div>
                      <p className="text-xs text-gray-400">Doctor Note</p>
                      <p>{item.doctorNote || "No note"}</p>
                    </div>

                    <div>
                      <p className="text-xs text-gray-400">Medicines</p>
                      {item.medicines?.length ? (
                        item.medicines.map((m, i) => (
                          <p key={i} className="text-xs bg-gray-100 px-2 py-1 rounded">
                            {m.name} - {m.dosage}
                          </p>
                        ))
                      ) : (
                        <p className="text-xs text-gray-400">No medicines</p>
                      )}
                    </div>

                    <div>
                      <p className="text-xs text-gray-400">Follow-up</p>
                      <p>{item.followUp || "No follow-up"}</p>
                    </div>
                  </div>
                )}

                {/* FOOTER */}
                <div className="flex justify-between items-center mt-4">
                  {isReady ? (
                    <span className="text-xs px-3 py-1 rounded-full bg-blue-50 text-blue-600">
                      Report Ready
                    </span>
                  ) : (
                    <span className="text-xs text-gray-400 italic">
                      No report available
                    </span>
                  )}


     {isReady && (
  <button onClick={() => handleDownload(item)}>
    <FaDownload className="text-gray-400 hover:text-[#00304e] cursor-pointer" />
  </button>
)}

                </div>
              </div>
            );
          })}
        </div>
)}
      </div>

  {selectedReport && (
  <div className="fixed inset-0 z-1990 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">

    {/* MODAL */}
    <div className="bg-white w-full max-w-2xl rounded-3xl shadow-2xl p-6 relative animate-fadeIn overflow-y-auto max-h-[90vh]">

      {/* CLOSE */}
      <button
        onClick={() => setSelectedReport(null)}
        className="absolute top-4 right-4 text-gray-400 hover:text-red-500 text-xl"
      >
        ✕
      </button>

      {/* HEADER */}
      <div className="flex items-center gap-4 mb-6  pb-4">
        <div className="p-3 bg-gradient-to-r from-[#00304e] to-[#005f73] rounded-xl shadow">
          <FaFileMedicalAlt className="text-white text-xl" />
        </div>

        <div>
          <h2 className="text-xl font-bold text-[#00304e]">
            Medical Report
          </h2>
          <p className="text-sm text-gray-500">
            {selectedReport.firstName}
          </p>
        </div>
      </div>

      {/* STATUS BADGE */}
      <div className="mb-4">
        <span className="px-4 py-1 text-xs rounded-full bg-blue-50 text-blue-600 font-medium">
          Report Ready
        </span>
      </div>

      {/* GRID INFO */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-5 text-sm">

        <div className="bg-gray-50 p-3 rounded-xl">
          <p className="text-gray-400 text-xs">Date</p>
          <p className="font-medium">📅 {new Date(selectedReport.appDate).toLocaleDateString()}</p>
        </div>

        <div className="bg-gray-50 p-3 rounded-xl">
          <p className="text-gray-400 text-xs">Contact</p>
          <p className="font-medium">📞 {selectedReport.mobNumber}</p>
        </div>

        <div className="bg-gray-50 p-3 rounded-xl">
          <p className="text-gray-400 text-xs">Room</p>
          <p className="font-medium">🏥 {selectedReport.roomNum || "—"}</p>
        </div>

        <div className="bg-gray-50 p-3 rounded-xl">
          <p className="text-gray-400 text-xs">Department</p>
          <p className="font-medium">🧾 {selectedReport.department || "General"}</p>
        </div>

      </div>

      {/* HEALTH ISSUE */}
      <div className="mb-5">
        <p className="text-xs text-gray-400 mb-1">Health Issue</p>
        <div className="bg-red-50 text-red-600 p-3 rounded-xl text-sm">
          {selectedReport.healthIssue || "No issue"}
        </div>
      </div>

      {/* DOCTOR NOTE */}
      <div className="mb-5">
        <p className="text-xs text-gray-400 mb-1">Doctor Note</p>
        <div className="bg-green-50 text-green-700 p-3 rounded-xl text-sm">
          {selectedReport.doctorNote || "No note"}
        </div>
      </div>

      {/* MEDICINES */}
      <div className="mb-5">
        <p className="text-xs text-gray-400 mb-2">Medicines</p>

        {selectedReport.medicines?.length ? (
          <div className="grid sm:grid-cols-2 gap-2">
            {selectedReport.medicines.map((m, i) => (
              <div
                key={i}
                className="bg-blue-50 text-blue-700 px-3 py-2 rounded-xl text-xs flex justify-between"
              >
                <span>{m.name}</span>
                <span className="font-medium">{m.dosage}</span>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-xs text-gray-400">No medicines</p>
        )}
      </div>

      {/* FOLLOW UP */}
      <div className="mb-6">
        <p className="text-xs text-gray-400 mb-1">Follow-up</p>
        <div className="bg-amber-50 text-amber-700 p-3 rounded-xl text-sm">
          {selectedReport.followUp || "No follow-up"}
        </div>
      </div>

      {/* FOOTER */}
      <div className="flex flex-col sm:flex-row justify-between items-center gap-3  pt-4">

        <span className="text-xs text-gray-500">
          Generated by hospital system
        </span>

        <button className="flex items-center gap-2 bg-gradient-to-r from-[#00304e] to-[#005f73] text-white px-5 py-2 rounded-xl shadow hover:scale-105 transition">
          <FaDownload /> Download Report
        </button>

      </div>
    </div>
  </div>
)}

    </div>
  );
}

export default PatientReports;